tracer.property: "I AM THE DEFAULT ACCOUNT CONFIGURATION"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://47.99.212.4:3306/blog_account_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8"
spring.datasource.username: "blog_account"
#Spring Config配置服务器要求所有已加密的属性前加上{cipher}，通知服务器处理已加密的值
spring.datasource.password: "{cipher}c7be12ec2408f4d01e9d1862b615c02686311ada701c4672a6ea47fc76574085"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"



