tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://47.99.212.4:3306/blog_content_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8"
spring.datasource.username: "blog_content"
#Spring Config配置服务器要求所有已加密的属性前加上{cipher}，通知服务器处理已加密的值
spring.datasource.password: "{cipher}13a670ef05472e99fdf99fa54005c31879338640d4d34f4277f2ac0eccc44e92"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"



