tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://47.99.212.4:3306/myblogdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8"
spring.datasource.username: "blog"
spring.datasource.password: "blog@2018"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

spring.datasource.testWhileIdle: "true"
signing.key: "345345fsdfsf5345"